### ISSUE TITLE
failure at times with child modules.

### ISSUE THREAD

**Issue by rdp** [mojohaus/webstart#37]
As a note, with beta 3, if I ran this:

$ mvn clean cm-package:package

everything worked (sorry cm-package is a local plugin :| )

However with beta 7, I get a NPE

{{{
Caused by: java.lang.NullPointerException
at org.codehaus.mojo.webstart.util.DefaultArtifactUtil.artifactContainsClass(DefaultArtifactUtil.java:211)
at org.codehaus.mojo.webstart.JnlpDownloadServletMojo.resolveJarResources(JnlpDownloadServletMojo.java:490)
at org.codehaus.mojo.webstart.JnlpDownloadServletMojo.execute(JnlpDownloadServletMojo.java:180)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
}}}

full trace:
http://betterlogic.com/roger/2016/05/maven-webstart-plugin-woe/

This only fails when performed from a "parent" module, if run in the child it works OK. Just thought I'd report it.

**Comment by tchemit** [comment]
Could you give us a example's project which prove the defect. thanks.
