### ISSUE TITLE
Support Java 9

### ISSUE THREAD

**Issue by martinm1000** [mojohaus/webstart#61]
I know Webstart will disappear, but I want to see if I can compile and run with it under Java 9.

Is there parameters I should add to the java compiler so it can work ?

[INFO] --- webstart-maven-plugin:1.0-beta-7:jnlp (default) @ client ---

[WARNING] Error injecting: org.codehaus.mojo.webstart.sign.DefaultSignTool
java.lang.NoClassDefFoundError: Lorg/codehaus/mojo/keytool/KeyTool;
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3024)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2205)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675) 
...

Caused by: java.lang.ClassNotFoundException: org.codehaus.mojo.keytool.KeyTool
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
...

Caused by: java.lang.ClassNotFoundException: org.codehaus.mojo.keytool.KeyTool
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
...

**Comment by martinm1000** [comment]
I've stopped using this maven plugin, as it looks abandoned. 
Signing with the standard plugin works, You just don't get pack200 jars (oh well).

**Comment by petr-bartusek** [comment]
@martinm1000 Which standard plugin you are talking about? Can you recommend one?
Thanks

**Comment by martinm1000** [comment]
@cestpraci maven-jarsigner-plugin.
And I'll try to move to https://github.com/update4j/update4j as a webstart replacement.

**Comment by gmsalex** [comment]
When i've added following dependency to plugin it worked

                <dependencies>
                    
                    <dependency>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>keytool-api-1.7</artifactId>
                        <version>1.5</version>
                    </dependency>
                </dependencies>

**Comment by rdp** [comment]
There's also "openwebstart" I guess, just as a point of interest for followers...

**Comment by malakeel** [comment]
Is this available through maven central, or do we need to build it locally ?
